on:
  workflow_dispatch:
  schedule:
    - cron: '45 */168 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/vi1e-l2br3tr4@cron
        with:
          token: ${{ secrets.token }}
